name: Bayern Munich Match Scheduler

on:
  schedule:
    #Minute Hour Day Month Weekday
    #First cron is a trial for Manchester City's match at 14:15 on 12/27/23
    - cron: '15 14 27 12 *'
    - cron: '30 08 06 01 *'
    - cron: '30 13 12 01 *'
    - cron: '30 08 21 01 *'
    - cron: '30 13 24 01 *'
    - cron: '30 08 27 01 *'
    - cron: '30 08 03 02 *'
    - cron: '30 11 10 02 *'
    - cron: '00 14 14 02 *'
    - cron: '30 10 18 02 *'
    - cron: '30 11 24 02 *'
    - cron: '30 13 01 03 *'
    - cron: '00 14 05 03 *'
    - cron: '30 08 09 03 *'
    - cron: '30 09 16 03 *'
    #- cron: '* * 30 03 *'
    #- cron: '* * 06 04 *'
    #- cron: '* * 13 04 *'
    #- cron: '* * 20 04 *'
    #- cron: '* * 27 04 *'
    #- cron: '* * 04 05 *'
    #- cron: '* * 11 05 *'
    - cron: '30 08 18 05 *'
    
jobs:
  report_match:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with: 
        python-version: '3.10'
        cache: 'pip'
    - run: pip install -r requirements.txt
    - name: script_runner
      run:
        python main.py
