name: Bayern Munich Match Scheduler

on:
  schedule:
    # Minute Hour Day Month Weekday, ALL TIME IS IN UTC 
    # No Daylight Savings Time: +6 hrs ahead CST
    # Daylight Savings Time: +5 hrs ahead of CST
    - cron: '30 14 06 01 *'
    - cron: '30 19 12 01 *'
    - cron: '30 14 21 01 *'
    - cron: '30 19 24 01 *'
    - cron: '30 14 27 01 *'
    - cron: '30 14 03 02 *'
    - cron: '00 18 10 02 *'
    - cron: '00 20 14 02 *'
    - cron: '30 16 18 02 *'
    - cron: '30 17 24 02 *'
    - cron: '30 19 01 03 *'
    - cron: '00 20 05 03 *'
    - cron: '30 14 09 03 *'
    - cron: '30 15 16 03 *'
    - cron: '30 18 30 03 *'
    - cron: '30 14 06 04 *'
    - cron: '00 20 09 04 *'
    - cron: '30 14 13 04 *'
    - cron: '00 20 17 04 *'
    - cron: '30 17 20 04 *'
    - cron: '30 14 27 04 *'
    - cron: '00 20 30 04 *'
    - cron: '30 14 04 05 *'
    - cron: '00 20 08 05 *'
    - cron: '30 16 12 05 *'
    - cron: '30 14 18 05 *'
    - cron: '30 17 10 08 *'
    - cron: '00 17 13 08 *'
    - cron: '45 19 16 08 *'
    - cron: '30 14 25 08 *'
    - cron: '30 16 01 09 *'
    - cron: '30 17 14 09 *'
    - cron: '05 22 17 09 *'
    - cron: '30 14 21 09 *'
    - cron: '30 17 28 09 *'
    - cron: '00 20 02 10 *'
    - cron: '30 16 06 10 *'
    - cron: '30 17 19 10 *'
    - cron: '00 20 23 10 *'
    - cron: '30 15 27 10 *'
    - cron: '45 20 30 10 *'
    - cron: '30 15 02 11 *'
    - cron: '00 20 06 11 *'
    - cron: '30 14 09 11 *'
    - cron: '30 19 22 11 *'
    - cron: '00 20 26 11 *'
    - cron: '30 17 30 11 *'
    - cron: '45 19 03 12 *'
    - cron: '30 14 07 12 *'
    - cron: '00 20 10 12 *'
    - cron: '30 14 14 12 *'
    - cron: '30 19 20 12 *'
    - cron: '00 17 06 01 *'
    - cron: '30 18 11 01 *'
    - cron: '30 19 15 01 *'
    - cron: '30 14 18 01 *'
    - cron: '00 20 22 01 *'
    - cron: '30 14 25 01 *'
    - cron: '00 20 29 01 *'
    - cron: '30 14 01 02 *'
    - cron: '30 19 07 02 *'
    - cron: '00 20 12 02 *'
    - cron: '30 17 15 02 *'
    - cron: '00 20 18 02 *'
    - cron: '30 16 23 02 *'
    - cron: '45 19 28 02 *'
    - cron: '00 20 05 03 *'
    - cron: '30 15 08 03 *'
    - cron: '10 22 11 03 *'
    - cron: '30 15 15 03 *'
    - cron: '30 14 29 03 *'
    - cron: '30 19 04 04 *'
    - cron: '30 19 08 04 *'
    - cron: '30 14 12 04 *'
    - cron: '00 19 16 04 *'
    - cron: '30 13 19 04 *'
    - cron: '30 13 26 04 *'
    - cron: '30 13 03 05 *'
    - cron: '30 13 10 05 *'
    - cron: '30 14 17 05 *'
    - cron: '00 16 15 06 *'
    - cron: '00 01 21 06 *'
    - cron: '00 19 24 06 *'

env: # Set the secrets as an environment variable
  access_token: ${{ secrets.ACCESS_TOKEN }}
  access_token_secret: ${{ secrets.ACCESS_TOKEN_SECRET }}
  api_key: ${{ secrets.API_KEY }}
  api_key_secret: ${{ secrets.API_KEY_SECRET }}
  bearer_token: ${{ secrets.BEARER_TOKEN }}
  client_secret: ${{ secrets.CLIENT_SECRET }}
  client_token: ${{ secrets.CLIENT_TOKEN }}

jobs:
  report_match:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with: 
        python-version: '3.10'
        cache: 'pip'
    - run: pip install -r requirements.txt
    - name: script_runner
      run:
        python main.py
