name: Bayern Munich Match Scheduler

on:
  schedule:
    #Minute Hour Day Month Weekday, ALL TIME IS IN UTC WHICH IS +6 HRS AHEAD OF CST
    - cron: '30 14 06 01 *'
    - cron: '30 19 12 01 *'
    - cron: '30 14 21 01 *'
    - cron: '30 19 24 01 *'
    - cron: '30 14 27 01 *'
    - cron: '30 14 03 02 *'
    - cron: '00 18 10 02 *'
    - cron: '00 20 14 02 *'
    - cron: '30 16 18 02 *'
    - cron: '30 17 24 02 *'
    - cron: '30 19 01 03 *'
    - cron: '00 20 05 03 *'
    - cron: '30 14 09 03 *'
    - cron: '30 15 16 03 *'
    - cron: '30 18 30 03 *'
    - cron: '30 14 06 04 *'
    - cron: '30 14 13 04 *'
    - cron: '30 17 20 04 *'
    #- cron: '* * 27 04 *'
    #- cron: '* * 04 05 *'
    #- cron: '* * 11 05 *'
    - cron: '30 14 18 05 *'
    
jobs:
  report_match:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with: 
        python-version: '3.10'
        cache: 'pip'
    - run: pip install -r requirements.txt
    - name: script_runner
      run:
        python main.py
